### ISSUE TITLE
Incorrect link removal in Full Network Set Generator

### ISSUE THREAD

**Issue by mattaustin222** [TravelModellingGroup/TMGToolbox#32] opened 2017-10-05 17:46 UTC
In the most recent change to FNSG/Remove Extra Links (last fall), Monika fixed the issue of some paths avoiding fare payment by traversing 'unused' links. Unfortunately, there appears to be a problem in which connections to some station nodes are incorrectly removed. Specifically, this can happen at the terminal station of unidirectional lines. For example, the Stouffville line operates in peak direction only today. In the PM, the transfer links at the terminal at Lincolnville are removed, yielded 0 alightings at the station. 

I suspect what is happening is that the tool searches for nodes that have transit segments leaving them and removes them from consideration. A terminal node of peak direction line only has segments arriving and is thus considered in the removal process.

**Comment by bilalyusuf** [comment] 2017-10-06 15:38
Hi Matt,
I looked into the issue and found that there was a condition missing such that when the start node is connected to a terminal station, it thinks there is no stop at the start node which is obviously not true. I fixed the bug in the latest version of remove extra links and it should be working properly now.

**Comment by PeterKucirek** [comment] 2017-10-11 14:03
@bilalyusuf does this mean the issue is resolved? @mattaustin222 can you confirm?

**Comment by bilalyusuf** [comment] 2017-10-11 14:12
In my internal tests, the issue has been resolved with the latest version of "Remove Extra Links" which should be in the dev branch of the toolbox. @mattaustin222 can confirm as well

**Comment by mattaustin222** [comment] 2017-10-11 14:34
@PeterKucirek I haven't had a chance to test Bilal's code yet. I'll chime in again once I've done some experimenting with it.

**Closed** 2017-10-13 14:58 UTC
Labels: bug
